CREATE TABLE `case_studies` (
	`id` text PRIMARY KEY NOT NULL,
	`slug` text NOT NULL,
	`client` text NOT NULL,
	`title` text NOT NULL,
	`industry` text NOT NULL,
	`category` text NOT NULL,
	`year` integer NOT NULL,
	`tagline` text NOT NULL,
	`hero_image` text NOT NULL,
	`gallery_images` text,
	`overview` text NOT NULL,
	`challenge` text NOT NULL,
	`strategy` text NOT NULL,
	`results` text,
	`testimonial` text,
	`deliverables` text,
	`external_url` text,
	`published` integer DEFAULT true NOT NULL,
	`created_at` text,
	`updated_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `case_studies_slug_unique` ON `case_studies` (`slug`);--> statement-breakpoint
CREATE TABLE `works` (
	`slug` text PRIMARY KEY NOT NULL,
	`num` text NOT NULL,
	`name` text NOT NULL,
	`title` text NOT NULL,
	`meta_description` text NOT NULL,
	`sector` text NOT NULL,
	`eyebrow` text,
	`category` text NOT NULL,
	`tag` text NOT NULL,
	`is_photo` integer DEFAULT false NOT NULL,
	`thumb` text NOT NULL,
	`tint` text,
	`intro` text NOT NULL,
	`is_case_study` integer DEFAULT false NOT NULL,
	`brand_logo` text,
	`cover_image` text,
	`quote` text,
	`notes` text,
	`color_pillars` text,
	`lede_paragraphs` text,
	`gallery` text,
	`next_link` text,
	`back_link` text
);
